### ISSUE TITLE
Send server records to GA.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/speaktome#104] opened 2017-07-25 21:15 UTC
Let's send some rudimentary success and failure metrics from the server to GA to help us understand and visualize how things go wrong, under what situations, and how it affects user retention.

**Comment by andrenatal** [comment] 2017-07-26 21:13
Guess we should move this to https://github.com/mozilla/speech-proxy?

**Comment by andrenatal** [comment] 2017-07-27 19:39
Duplicate of: https://github.com/mozilla/speech-proxy/issues/46

**Closed by andrenatal** 2017-07-27 19:39 UTC
