### ISSUE TITLE
The "Voice Fill" button is not displayed on specific websites

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/speaktome#176] opened 2017-09-01 14:52 UTC
**Notes**
- The issue is reproducible on the following websites:
                  1) www.google.co.ck ;
                  2) www.google.com.eg .

**[Affected versions]:**
- Firefox 55.0.3 and up
- Voice Fill 1.3.0

**[Affected Platforms]:**
- All Windows
- All Mac OS
- All Linux

**[Prerequisites]:**
- Latest Voice Fill add-on (1.3.0) was previously installed on a clean profile.

**[Steps to reproduce]:**
  1.Open the browser with the profile from prerequisites and navigate to "www.google.co.ck" page.
  2.Observe the "Voice Fill" button.

**[Expected result]:**
- The "Voice Fill" button is displayed on the right side of the Search bar.

**[Actual result]:**
- The "Voice Fill" button is not displayed at all.

**[Notes]:**
- Attached a screen recording of the issue:
![voice fill button](https://user-images.githubusercontent.com/31243259/29975132-feaa7148-8f3d-11e7-9f7c-71b0c14b7133.png)

**Comment by pdehaan** [comment] 2017-09-01 15:22
I don't see www.google.co.ck or www.google.com.eg listed in the manifest.json file (but I _do_ see a    www.google.eg):

https://github.com/mozilla/speaktome/blob/9b00d951517bd5b009fa04af2ade9ef49fc6f192/extension/manifest.json#L22-L432

**Comment by Softvision-MariusComan** [comment] 2017-09-01 15:43
We use for testing the list from "content.js", however those two websites are not also displayed in the manifest.json file.
Should we use the list from "manifest.js" when testing? Also the links should not be in both lists?

**Comment by marwendoukh** [comment] 2017-09-04 07:52
I think this issue needs to be closed (PR merged)

**Comment by Softvision-MariusComan** [comment] 2017-09-04 07:55
I've retested this issue and the "Voice fill" button is now displayed on both websites. Marking as verified.

**Comment by Softvision-MariusComan** [comment] 2017-09-04 12:52
We finised testing "Voice Fill" on all Google domains and the issue is still reproducible on the following websites:

**Comment by marwendoukh** [comment] 2017-09-04 13:19
Hello @Softvision-MariusComan , I can't reproduce for : 

- https://www.google.com.et

Try to use the HTTPS version for : 

1. https://www.google.sr

2. https://www.google.com.mm

**Comment by Softvision-MariusComan** [comment] 2017-09-04 14:15
If I use HTTPS version for google.sr and google.com.mm, "Voice fill" button is correctly displayed.
However I still can reproduce the issue for https://www.google.com.et domain, on Windows and also on Mac.


![google com et](https://user-images.githubusercontent.com/31243259/30029899-c3cda8d0-9193-11e7-8a59-1683bb7b42d6.png)

**Comment by Softvision-CristinaBadescu** [comment] 2017-09-04 14:55
I have tried to test the "http://google.com.on/" Google domain but redirects me to a server error page. However, the link is displayed on both Google domain list (content.js  and manifest.json).

I also cannot test the "https://www.google.us" Google domain, because it redirects me to "https://www.google.com" page.

**Comment by marwendoukh** [comment] 2017-09-04 18:18
@Softvision-CristinaBadescu  Thank you , I have fixed that.
@Softvision-MariusComan I am still looking for the problem of google.com.et .

**Comment by marwendoukh** [comment] 2017-09-10 09:05
@Softvision-MariusComan  Could you reproduce this on the English version of google.com.et ?

**Comment by Softvision-MariusComan** [comment] 2017-09-11 12:20
Yes, I still can reproduce the issue for google.com.et domain.
![google com et](https://user-images.githubusercontent.com/31243259/30274049-6d3e9940-9704-11e7-83fa-ee047722a28c.gif)

**Comment by johngruen** [comment] 2017-09-20 21:02
Closing b/c i think this is fixed in the latest version

**Closed by johngruen** 2017-09-20 21:02 UTC

**Comment by Softvision-MariusComan** [comment] 2017-09-21 08:11
The issue in no longer reproducible on Windows 10 x64, Ubuntu 14.04 x64 and Mac 10.12 with the latest version of Voice Fill 1.3.1 (built on 2017-09-21) installed.
