### ISSUE TITLE
Add to Address bar

### ISSUE THREAD

**Issue by AmrEldib** [mozilla/speaktome#157] opened 2017-08-06 15:44 UTC
I almost never use DuckDuckGo's home page to start a search. I use the address bar.  
It would be great if voice search is added to the address bar. It could be an icon next to the refresh button on the right side, or a shortcut that enables it like Alt+D

**Comment by SoftVision-CarmenFat** [comment] 2017-08-14 14:22
Hi @AmrEldib and thanks for the report.

However, this is a dupe of [146](https://github.com/mozilla/speaktome/issues/146).

**Comment by johngruen** [comment] 2017-08-29 18:19
Closing in favor or #146

**Closed by johngruen** 2017-08-29 18:19 UTC
